name: TeensyROM WPF UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Source/Windows/TeensyRom.Ui/TeensyRom.Ui.sln
      Project_Name: Source/Windows/TeensyRom.Ui/src/TeensyRom.Ui/TeensyRom.Ui.csproj  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET SDK
    - name: Install .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the application
    - name: Build the application
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore
