name: TeensyROM UI WPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Source/Windows/TeensyRom.Ui/TeensyRom.Ui.sln
      Project_Path: Source/Windows/TeensyRom.Ui/src/TeensyRom.Ui/
      Project_Name: TeensyRom.Ui.csproj  
      Publish_File_Name: tr-ui-${{ github.run_number }}.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build Application
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish Application
      run: dotnet publish ${{ env.Project_Path }}${{ env.Project_Name }} -c ${{ matrix.configuration }} --self-contained true -r win-x64 -o ${{ github.workspace }}\published\

    - name: Archive Build Artifacts
      run: 7z a ${{ env.Publish_File_Name }} ${{ github.workspace }}\published\*
      shell: pwsh

    - name: Create Tag
      id: create_tag
      run: |
       $date = Get-Date -Format "yyyyMMdd-HHmmss"
       $sha = "${{ github.sha }}"
       $tag = "v$date-$sha".Substring(0,15)
       echo "::set-output name=tag::$tag"
      shell: pwsh

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v1      
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ steps.create_tag.outputs.tag }}
       files: ${{ env.Publish_File_Name }}