name: Build WPF Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    env:
      Solution_Name: Source/Windows/TeensyRom.Ui/TeensyRom.Ui.sln
      Project_Path: Source/Windows/TeensyRom.Ui/src/TeensyRom.Ui/
      Project_Name: TeensyRom.Ui.csproj
      Publish_File_Name: tr-ui-${{ github.run_number }}.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
         restore-keys: |
          ${{ runner.os }}-nuget-

      - name: Install NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build Application
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

      - name: Publish Application
        run: dotnet publish ${{ env.Project_Path }}${{ env.Project_Name }} -c ${{ matrix.configuration }} -r win-x64 -o ${{ github.workspace }}\published\

      - name: Archive Build Artifacts
        run: 7z a ${{ env.Publish_File_Name }} ${{ github.workspace }}\published\*
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build-artifact
          path: ${{ env.Publish_File_Name }}

  tag:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Create and Push Tag
        run: |
          $date = Get-Date -Format "yyyyMMdd-HHmmss"
          $tag = "build-$date"
          git tag $tag
          git push origin $tag
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}